name    'leonardothibes-jekyll'
author  'leonardothibes'
version '1.0.3'
license 'MIT'
summary 'Manage Jekyll via Puppet'
description 'Manage Jekyll via Puppet'
source 'git://github.com/leonardothibes/puppet-jekyll.git'
project_page 'http://github.com/leonardothibes/puppet-jekyll'
