name 'leonardothibes-jekyll'
version '1.0.0'
author 'leonardothibes'
license 'MIT'
summary 'Manage Jekyll via Puppet'
description 'Manage Jekyll via Puppet'
source 'git://github.com/leonardothibes/puppet-jekyll.git'
project_page 'http://documentup.com/leonardothibes/puppet-jekyll'
